version: "2.4"
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    command: ["-conf", "/etc/selenoid/browsers.json", "-log-output-dir", "/opt/selenoid/logs", "-video-output-dir", "/opt/selenoid/video"]
    ports:
      - 4444:4444
    volumes:
      - "./etc/selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./etc/selenoid/logs:/opt/selenoid/logs"
      - "./etc/selenoid/video:/opt/selenoid/video"
  selenoid-ui:
    network_mode: bridge
    image: aerokube/selenoid-ui:latest-release
    ports:
      - 8080:8080
    links:
      - selenoid